backend:
    name: github
    repo: sinnpotential/friedmannschmuck.ch
    branch: master

media_folder: images/uploads

collections:
    - name: jewelry 
      label: Schmuck
      folder: _jewelry
      create: true
      fields:
          - label: Name
            name: title
          - label: Beschreibung
            name: description
